### ISSUE TITLE
Combine four images to one

### ISSUE THREAD

**Issue by ChrisBr** [digitaltom/photobooth#1]
![result](https://cloud.githubusercontent.com/assets/3799140/16410254/e9b8292a-3d21-11e6-9579-082ac82b8c7c.jpg)

@digitaltom what do you think about it?

**Comment by digitaltom** [comment]
Looks good! Maybe another font?

**Comment by ChrisBr** [comment]
Yeah! I already thought about that... Need to first check which fonts are available by default in our raspberry images. Any preferences?

**Comment by digitaltom** [comment]
See https://github.com/digitaltom/photobooth/pull/2
