### ISSUE TITLE
Pictures license

### ISSUE THREAD

**Issue by Ana06** [digitaltom/photobooth#35]
It would be nice to add a license for this picture: https://user-images.githubusercontent.com/582520/43478387-0dd809d4-94fe-11e8-8464-9873e775c56c.jpg

I am going to add it in a presentation as a example of a cool Hackweek project (for a talk tomorrow at university about open source, openSUSE and SUSE). I guess (and hope) that this is fine for you @digitaltom :pray: Adding a license would save having to ask

**Comment by digitaltom** [comment]
Feel free to use it! :-) I can add a license later.

**Comment by digitaltom** [comment]
Added CC Attribution license.
